name: cors_enabler
description: A CORS proxy to make any API server CORS-compliant.
version: 0.9.1+2
repository: https://github.com/d-markey/cors_enabler_dart

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints:
  test:
